apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: bomlo-alerts-fss
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: '#team-bømlo-ops'
      prependText: '<!redteam>'
  route:
    group_wait: 2m
    repeat_interval: 1h
    group_interval: 5m
  alerts:
    - alert: bomlo-errorlogging
      expr: (100 * sum by (log_app) (rate(logd_messages_total{team="tbd",log_level="Error"}[5m])) / sum by (log_app) (rate(logd_messages_total{team="tbd"}[5m]))) > 10
      for: 2m
      description: "Høy feilrate: {{  $value | printf \"%.1f\" }} % i {{ $labels.log_app }} "
      action: "Undersøk <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|loggene> eller se <https://github.com/navikt/tbd/blob/master/redteam-wiki/kjente_feil.md|kjente feil>"
      severity: danger
    - alert: bomlo-kafka-lag
      expr:  sum(kafka_consumergroup_group_topic_sum_lag{group=~"^tbd-.+",group!="tbd-sparkel-stonadsstatistikk-v1",group!="tbd-sparkel-oppgaver-v1",group!="tbd-sparkel-arbeidsgiver-v1",group!="tbd-sparkel-gosys-v1"}) by (group,topic) > 10000
      for: 2m
      description: '{{ $labels.app }} har {{ $value }} consumer lag mot {{ $labels.topic }}'
      action: "Prøv <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|loggene>"
      severity: danger
    - alert: bomlo-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{team="tbd"}[30m])) by (container) > 2
      for: 5m
      description: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
      action: "Undersøk <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|loggene>"
      severity: warning
