apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: bomlo-alerts
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: '#team-bømlo-ops'
      prependText: '<!subteam^S010U3KQ8LQ|redteam> - '
      send_resolved: true
      username: 'En bot'
      icon_emoji: ':naiser:'
  route:
    repeat_interval: 3h
  alerts:
    - alert: errorRate
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_team="tbd",log_level="Error", log_app!="speil"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_team="tbd", log_app!="speil"}[5m]))) > 10
      for: 5m
      description: "Høy feilrate: {{  $value | printf \"%.1f\" }} % i {{ $labels.log_app }} "
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg>, <https://logs.adeo.no/goto/2ca24549a47f3749299e3214261f7e29|vanlig logg> og <https://github.com/navikt/tbd/blob/master/redteam-wiki/kjente_feil.md|kjente feil>"
      severity: danger
    - alert: appDown
      expr: up{team="tbd",app!="speil",job="kubernetes-pods"} == 0
      for: 10m
      description: "{{ $labels.app }} er nede"
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg> og <https://logs.adeo.no/goto/2ca24549a47f3749299e3214261f7e29|vanlig logg>"
      severity: warning
    - alert: speilDown
      expr: up{team="tbd",app="speil",job="kubernetes-pods"} == 0
      for: 2m
      description: "Speil er nede"
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg> og <https://logs.adeo.no/goto/2ca24549a47f3749299e3214261f7e29|vanlig logg>"
      severity: danger
    - alert: httpErrors
      severity: danger
      expr: sum(rate(traefik_backend_requests_total{code!~"^[23].*", backend=~"speil.nais.adeo.no/"}[5m])) by (backend) /  sum(rate(traefik_backend_requests_total{backend=~"speil.nais.adeo.no/"}[5m])) by (backend) > 20
      for: 2m
      description: "{{ $labels.backend }} gir {{ value | printf \"%.1f\" }} % HTTP feilresponser"
      action: "Sjekk <https://logs.adeo.no/goto/2ca24549a47f3749299e3214261f7e29|logg> og <https://logs.adeo.no/goto/f475a9aa2de203263830c7945b701234|sikkerlogg>"
    - alert: Lengre enn 26 timer siden forrige avstemmingsjobb ble fullført
      severity: danger
      expr: (time() - avstemming) > 93600
      for: 3m
      action: "Se <https://logs.adeo.no/goto/6994bbd9fff4517cc058d87bce4bd404|vanlig logg>  og kubectl describe cronjob spenn-avstemming i prod-fss/tbd"
