apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: bomlo-alerts
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: '#team-bømlo-alerts'
      prependText: '<!subteam^S010U3KQ8LQ|redteam> - '
      send_resolved: true
      username: 'En bot'
      icon_emoji: ':gcp:'
  route:
    repeat_interval: 3h
  alerts:
    - alert: errorRate
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_team="tbd",log_level="Error"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_team="tbd"}[5m]))) > 10
      for: 5m
      description: "Høy feilrate: {{  $value | printf \"%.1f\" }} % i {{ $labels.log_app }} "
      action: "Sjekk logger"
      severity: danger
    - alert: appDown
      expr: max(up{team="tbd",job="kubernetes-pods"}) by (app) == 0
      for: 10m
      description: "{{ $labels.app }} er nede"
      action: "Sjekk logger"
      severity: danger
    - alert: Økende Consumer Lag
      expr: label_replace(sum(delta(kafka_consumergroup_group_topic_sum_lag{group=~"^tbd-.*", group!="tbd-speaker-v1", group!="tbd-sparkel-stonadsstatistikk-v1", group!="tbd-sparkel-oppgaver-v1", group!="tbd-sparkel-arbeidsgiver-v1", group!="tbd-sparkel-gosys-v1", group!="tbd-spre-saksbehandlingsstatistikk-v3", group!~"tbd-spangre-utsettelser-.*", group!~"tbd-spre-subsumsjon.*"}[5m])) by (group, topic) / (5*60), "groupname", "$1", "group", "^tbd-(.*)") > 5
      for: 5m
      description: 'consumer group *{{ $labels.groupname }}* øker med  {{ $value }} pr sekund på *{{ $labels.topic }}*'
      action: "Sjekk logger"
      severity: danger
    - alert: Økende Consumer Lag - spedisjon
      expr: sum(delta(kafka_consumergroup_group_topic_sum_lag{group="spedisjon-v1" }[5m])) by(group, topic)/(5*60) >5
      for: 5m
      description: 'consumer group *{{ $labels.group }}* øker med  {{ $value }} pr sekund på *{{ $labels.topic }}*'
      action: "Sjekk logger"
      severity: danger
    - alert: Økende Consumer Lag - datavarehus
      expr: sum(delta(kafka_consumergroup_group_topic_sum_lag{topic="tbd.aapen-sykepenger-saksbehandlingsstatistikk" }[5m])) by(group, topic)/(5*60)>5
      for: 5m
      description: 'consumer group *{{ $labels.group }}* øker med  {{ $value }} pr sekund på *{{ $labels.topic }}*'
      action: "Sjekk logger"
      severity: danger

