apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: bomlo-alerts-gcp
  namespace: tbd
  labels:
    team: tbd
spec:
  receivers:
    slack:
      channel: '#team-bømlo-ops'
      prependText: '<!subteam^S010U3KQ8LQ|redteam>'
      send_resolved: true
      username: 'Jeg er bare en stakkars bot'
      icon_emoji: ':fire:'
  route:
    group_wait: 2m
    repeat_interval: 1h
    group_interval: 5m
  alerts:
    - alert: bomlo-errorlogging
      expr: (100 * sum by (log_app) (rate(logd_messages_total{log_team="tbd",log_level="Error", log_app!="speil"}[5m])) / sum by (log_app) (rate(logd_messages_total{log_team="tbd", log_app!="speil"}[5m]))) > 10
      for: 5m
      description: "Høy feilrate: {{  $value | printf \"%.1f\" }} % i {{ $labels.log_app }} "
      action: "Undersøk <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg>, <https://logs.adeo.no/goto/f781398321efa9651aadd16236179899|vanlig logg> eller se <https://github.com/navikt/tbd/blob/master/redteam-wiki/kjente_feil.md|kjente feil>"
      severity: danger
    - alert: bomlo-kafka-lag
      expr:  sum(kafka_consumergroup_group_topic_sum_lag{group=~"^tbd-.+",group!="tbd-sparkel-stonadsstatistikk-v1",group!="tbd-sparkel-oppgaver-v1",group!="tbd-sparkel-arbeidsgiver-v1",group!="tbd-sparkel-gosys-v1"}) by (group,topic) > 10000
      for: 2m
      description: '{{ $labels.app }} har {{ $value }} consumer lag mot {{ $labels.topic }}'
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg> eller <https://logs.adeo.no/goto/f781398321efa9651aadd16236179899|vanlig logg>"
      severity: danger
    - alert: bomlo-kontinuerlig-restart
      expr: sum(increase(kube_pod_container_status_restarts_total{namespace="tbd"}[30m])) by (container) > 3
      for: 5m
      description: "{{ $labels.container }} har restartet flere ganger siste halvtimen!"
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg> eller <https://logs.adeo.no/goto/f781398321efa9651aadd16236179899|vanlig logg>"
      severity: warning
    - alert: bomlo-app-nede
      expr: up{team="tbd",job="kubernetes-pods"} == 0
      for: 5m
      description: "{{ $labels.app }} er nede"
      action: "Se <https://logs.adeo.no/goto/e16670da1103009f63d8f4c663f26be8|sikkerlogg> eller <https://logs.adeo.no/goto/f781398321efa9651aadd16236179899|vanlig logg>"
      severity: warning
